---
sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
    - libcurl3
    - libcurl4-gnutls-dev
    - python-docutils

before_install:
  - set -e
  - wget --no-check-certificate https://repo.varnish-cache.org/source/varnish-4.1.4.tar.gz
  - tar zxvf varnish-*.tar.gz
  - pushd varnish-*
  - ./autogen.sh
  - ./configure
  - make -sj32
  - sudo make PREFIX="/usr/local" install
  - sudo ldconfig
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j1

compiler:
  - clang
  - gcc
