---
sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
    - libcurl3
    - libcurl4-gnutls-dev
    - python-docutils

before_install:
  - set -e
  - git clone https://github.com/varnishcache/varnish-cache.git ./varnish
  - pushd varnish
  - ./autogen.sh
  - ./configure
  - make -sj32
  - sudo make PREFIX="/usr/local" install
  - popd
  - sudo ldconfig

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j1

compiler:
  - clang
  - gcc
